version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: arapp_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://dev:dev@postgres:5432/arapp_dev?schema=public
      JWT_SECRET: supersecretkey123
      JWT_EXPIRES_IN: 1d
      ENCRYPTION_KEY: 8a31efb9c02bd78ccf2f45e4bcd44a8120f6d62eac943e4b7285a4dbe4dff209
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app                  # Kodlar senin bilgisayarından okunur
      - /app/node_modules               # node_modules container içinde kalır

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: http://backend:3000  # Backend container adı üzerinden bağlantı
    ports:
      - "5173:5173"  # Vite dev server
    depends_on:
      - backend
    volumes:
      - ./frontend:/app                 # Kodlar host → container
      - /app/node_modules               # node_modules container içinde

volumes:
  db_data:
